name: Generate lockfile

on:
  push:
    branches:
      - 'phase21-rc1'
    paths:
      - '.github/workflows/generate-lockfile.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lockfile:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87
        with:
          toolchain: 1.85.1
      - run: cargo +1.85.1 generate-lockfile
      - run: cargo +1.85.1 check --locked --all-targets
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: Cargo.lock-1.85.1
          path: Cargo.lock
          if-no-files-found: error
